version: '3'
services:
  mysql-standalone:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin123 
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    ports:
      - 3306:3306

  springboot-docker-container: 
   image: springboot-docker-container
   build:
     context: ./
     dockerfile: Dockerfile
   ports:
     - 8090:8080
   depends_on:
     - mysql-standalone
